Repository astro-group-bristol/Gradus.jl, pull requests merged in 2023-02, with the labels that each got.

#74 Feat: work in progress disc profiles
  Project.toml
  docs/src/examples/examples.jl
  docs/src/examples/examples.md
  docs/src/internals/custom-metrics.md
  docs/src/internals/special-radii.md
  src/Gradus.jl
  src/corona-to-disc/disc-profiles.jl
  src/line-profiles.jl
  src/point-functions.jl
  src/transfer-functions/cunningham-transfer-functions.jl
  src/transfer-functions/precision-solvers.jl
  src/transfer-functions/transfer-functions-2d.jl
  src/utils.jl
  test/integration/test-inference.jl
  test/line-profiles/test-api.jl
  test/line-profiles/test-binning.jl
  test/line-profiles/test-cunningham.jl
  test/runtests.jl
  test/smoke-tests/line-profiles.jl
  test/transfer-functions/test-2d.jl
  test/utils.jl
Labels: enhancement, optimization, analysis

#77 Chore: move angle mapping function
  Project.toml
  src/corona-to-disc/corona-models.jl
  src/corona-to-disc/sky-geometry.jl
Labels: geometry

#71 Updated examples.md to use new syntax
  .gitignore
  docs/src/examples/examples.md
  src/transfer-functions/precision-solvers.jl
Labels: documentation

#83 Feat: SVector as common currency
  Project.toml
  src/Gradus.jl
  src/tracing/constraints.jl
  src/tracing/method-implementations/auto-diff.jl
  src/tracing/tracing.jl
  src/tracing/utility.jl
  test/smoke-tests/tracegeodesics.jl
Labels: integrator

#85 Feat: better put out the bins for garbage collection
  Project.toml
  src/Gradus.jl
  src/GradusBase/geodesic-solutions.jl
  src/accretion-geometry/bootstrap.jl
  src/image-planes/planes.jl
  src/line-profiles.jl
  src/tracing/constraints.jl
  src/tracing/method-implementations/first-order.jl
  src/tracing/tracing.jl
  src/tracing/utility.jl
  src/transfer-functions/precision-solvers.jl
  src/transfer-functions/transfer-functions-2d.jl
  src/utils.jl
Labels: optimization

#88 Feat: render unto first-order
  Project.toml
  benchmark/integrator/benchmark-tracing.jl
  benchmark/runbenchmarks.jl
  src/Gradus.jl
  src/GradusBase/GradusBase.jl
  src/GradusBase/geodesic-solutions.jl
  src/GradusBase/metric-params.jl
  src/rendering/rendering.jl
  src/rendering/utility.jl
  src/tracing/callbacks.jl
  src/tracing/method-implementations/first-order.jl
  src/tracing/tracing.jl
Labels: integrator

#90 Feat: charts
  Project.toml
  src/Gradus.jl
  src/line-profiles.jl
  src/orbits/orbit-interpolations.jl
  src/special-radii.jl
  src/tracing/callbacks.jl
  src/tracing/charts.jl
  src/tracing/method-implementations/first-order.jl
  src/tracing/tracing.jl
  src/transfer-functions/cunningham-transfer-functions.jl
  src/transfer-functions/integration.jl
  src/transfer-functions/transfer-functions-2d.jl
  test/integration/test-charts.jl
  test/runtests.jl
Labels: integrator

#91 Feat: disc emissivity
  Project.toml
  src/Gradus.jl
  src/corona-to-disc/corona-models.jl
  src/corona-to-disc/disc-profiles.jl
  src/transfer-functions/cunningham-transfer-functions.jl
  src/transfer-functions/transfer-functions-2d.jl
  src/transfer-functions/types.jl
Labels: analysis
